# Server
server.port=8081

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/clothesvnua?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456



spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=false

# URL FE, neu co nhieu nguon thi them vao(localhost,localhost1)
cors.allowed-origins=http://localhost:5173,http://localhost:8080

#Duong dan tuyet doi de luu anh
#bat buoc phai có /uploads/
#file.upload-dir=D:/JAVA/spring/quanao/quanao-be/uploads/
file.upload-dir=storage/uploads


jwt.secret=DayLaMotChuoiBiMatRatDaiVaAnToanDeMaHoaJWTPhaiDaiHon256Bit
jwt.expiration-ms=86400000  

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB


#CONFIG GMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=duyav1411@gmail.com
spring.mail.password=bvsz hbem kejd mvwx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8


# VNPay Configuration
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8081/api/vnpay/payment-return
vnpay.tmn-code=LBMEROG7
vnpay.secret-key=8ODEGEIEU7HZC9QSCZN1XKNZUFNU1QB5
vnpay.api-url=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
# Các c?u hình thêm (tùy ch?n)
vnpay.version=2.1.0
vnpay.command=pay
vnpay.currency-code=VND
vnpay.locale=vn

